# Tableaux et matrices

La définition de tableaux i.e. vecteurs, matrices, hypermatrices est un élément essentiel de Julia.

Julia ne possède qu'un seul type de tableau : **Array** on peut définir son nombre d'entrées (1 entrée= 1 dimension ...) et son contenu de façon assez générale. Un tableau peut contenir des matrices à chaque élément.

Une particularité est que les indices de tableaux commencent à 1, et l'accès aux éléments se fera à l'aide de `[` `]` et non `(` `)` qui est réservé aux fonctions.

Avant de rentrer dans la construction et manipulation de tableau regardons une autre classe 

# Iterateur

Julia possède un Type particulier fait à l'aide du ":"

In [1]:
a = 1:5

1:5

In [2]:
a .+ 1

2:6

In [3]:
typeof(a)

UnitRange{Int64}

In [4]:
b = 0:0.5:2

0.0:0.5:2.0

In [5]:
typeof(b)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

Ce type "formel" permet d'avoir une définition et une méthode associée sans stocker l'ensemble des valeurs. Attention celui-ci peut être vide :

In [6]:
d=1:0 # itérateur formel mais correspond à un ensemble vide de valeurs

1:0

In [7]:
collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [8]:
d  = 1:10  |> sum

55

# Tableau

On vient de voir que l'on peut transformer l'itérateur précédent en tableau à l'aide de la commande "collect"

In [9]:
a = 1:5
aa = collect(complex.(a)) .+ 1im

5-element Vector{Complex{Int64}}:
 1 + 1im
 2 + 1im
 3 + 1im
 4 + 1im
 5 + 1im

In [10]:
[aa aa]'

2×5 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-1im  2-1im  3-1im  4-1im  5-1im
 1-1im  2-1im  3-1im  4-1im  5-1im

In [11]:
transpose([aa aa])

2×5 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1+1im  2+1im  3+1im  4+1im  5+1im
 1+1im  2+1im  3+1im  4+1im  5+1im

In [12]:
permutedims([aa aa])

2×5 Matrix{Complex{Int64}}:
 1+1im  2+1im  3+1im  4+1im  5+1im
 1+1im  2+1im  3+1im  4+1im  5+1im

In [13]:
a = collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [14]:
a'a

55

In [15]:
typeof(aa)

Vector{Complex{Int64}} (alias for Array{Complex{Int64}, 1})

La réponse est de la forme **Array{Type,dim}** un tableau de **Type** à **dim** entrées (1 pour vecteur, 2 pour matrices ...)

A remarquer :
* l'indexation des tableaux commence à 1.
* un tableau à une entrée est vu comme un vecteur colonne par défaut.
* le crochet [ ] sert à extraire ou affecter une valeur ou un bloc de valeur. Attention le crochet [ ] sert également de "concatenateur" et constructeur de tableau (voir suite)
* Il est possible de faire des tableaux de n'importe quoi (fonction, tableau, ...).

In [16]:
aa[1]

1 + 1im

In [17]:
aa[begin] # pour accèder au premier élément

1 + 1im

In [18]:
aa[end] # pour accèder au dernier élément

5 + 1im

In [19]:
first(a), last(a)

(1, 5)

In [20]:
first(a,3)

3-element Vector{Int64}:
 1
 2
 3

In [21]:
aa[end-2:end] .= 1 ; println(aa)

Complex{Int64}[1 + 1im, 2 + 1im, 1 + 0im, 1 + 0im, 1 + 0im]


Les crochets permettent la construction explicite de tableaux (ou leur concaténation)

In [22]:
A = [1 2 ; 3 4] # {espace} = séparateur de colonne

2×2 Matrix{Int64}:
 1  2
 3  4

In [23]:
AA=[A  A] # concaténation par bloc

2×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4

In [24]:
hcat(A, A) # commande équivalent à la précédente [A  A]

2×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4

In [25]:
AA = [A ; A]

4×2 Matrix{Int64}:
 1  2
 3  4
 1  2
 3  4

In [26]:
vcat(A,A) # commande équivalent à la précédente [A  ; A]

4×2 Matrix{Int64}:
 1  2
 3  4
 1  2
 3  4

In [27]:
stack([A A])

2×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4

On peut accéder à tout ou partie d'un tableau à l'aide de 2 indices

In [28]:
A[2,1]

3

In [29]:
A[2,:]

2-element Vector{Int64}:
 3
 4

In [30]:
A[:,2]

2-element Vector{Int64}:
 2
 4

In [31]:
A[end,end]

4

In [32]:
AA

4×2 Matrix{Int64}:
 1  2
 3  4
 1  2
 3  4

In [33]:
sum(AA, dims=2)

4×1 Matrix{Int64}:
 3
 7
 3
 7

In [34]:
B = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [35]:
B = [1;2;3;4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [36]:
for i in eachindex(AA)
    println(i)
end

1
2
3
4
5
6
7
8


In [37]:
for row ∈ eachrow(AA)
    println("$row")
end

[1, 2]
[3, 4]
[1, 2]
[3, 4]


In [38]:
for i = axes(AA, 1)
    println("$(AA[i,:])")
end

[1, 2]
[3, 4]
[1, 2]
[3, 4]


A noter que l'on peut faire des tableaux de tout type voir de les mélanger (Any)

In [39]:
a=["un";"deux"]

2-element Vector{String}:
 "un"
 "deux"

In [40]:
b=[1>2,true,false]

3-element Vector{Bool}:
 0
 1
 0

In [41]:
c=["un"; 2 ; true]

3-element Vector{Any}:
     "un"
    2
 true

Le crochet [ ] permet également la construction rapide de matrice ou tableau comme le montre l'exemple ci-dessous pour construire une matrice de VanderMonde

$$ V_{i,j}=x_i^{j-1}$$

In [42]:
[ 2i+3 for i in 1:7 if i%3 == 0]

2-element Vector{Int64}:
  9
 15

In [43]:
x = 0:0.2:1
V = [ x[i]^(j-1) for i=1:6, j=1:6] # ligne et colonne

6×6 Matrix{Float64}:
 1.0  0.0  0.0   0.0    0.0     0.0
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0

In [44]:
V = zeros(Float64, 6,6)
for j in 1:6, i in 1:6
    V[i,j] = x[i]^(j-1)
end
V

6×6 Matrix{Float64}:
 1.0  0.0  0.0   0.0    0.0     0.0
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0

In [45]:
D=[ u*v for u=1:0.5:3, v=1:0.5:4]

5×7 Matrix{Float64}:
 1.0  1.5   2.0  2.5   3.0   3.5    4.0
 1.5  2.25  3.0  3.75  4.5   5.25   6.0
 2.0  3.0   4.0  5.0   6.0   7.0    8.0
 2.5  3.75  5.0  6.25  7.5   8.75  10.0
 3.0  4.5   6.0  7.5   9.0  10.5   12.0

On peux évidemment faire des tableaux à 3,4... entrèes.

## Manipulation de Tableau

### push!

Le fonction push permet d'ajouter à un tableau une valeur supplémentaire

In [46]:
a = Int[]
push!(a,1)     # => [1]
push!(a,2)     # => [1,2]
push!(a,4)     # => [1,2,4]
push!(a,6)     # => [1,2,4,6]

4-element Vector{Int64}:
 1
 2
 4
 6

### append!

Cette fonction permet de mettre bout à bout 2 tableaux

In [47]:
append!(a,a)

8-element Vector{Int64}:
 1
 2
 4
 6
 1
 2
 4
 6

In [48]:
A = []
push!(A, 1)

1-element Vector{Any}:
 1

A noté le  **Array{Any,1}** !

In [49]:
a = ComplexF64[]
push!(a,1)     # => [1]
push!(a,2)     # => [1,2]
push!(a,4)     # => [1,2,4]
push!(a,6)  

4-element Vector{ComplexF64}:
 1.0 + 0.0im
 2.0 + 0.0im
 4.0 + 0.0im
 6.0 + 0.0im

In [50]:
a = zeros(0)

Float64[]

In [51]:
a = zeros(Int32,1)

1-element Vector{Int32}:
 0

In [52]:
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [53]:
fill(5, (6,6))

6×6 Matrix{Int64}:
 5  5  5  5  5  5
 5  5  5  5  5  5
 5  5  5  5  5  5
 5  5  5  5  5  5
 5  5  5  5  5  5
 5  5  5  5  5  5

### Attention sur la conversion de type !

In [54]:
a = collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [55]:
a = fill(0.,3,2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [56]:
a[2] = sqrt(2)

1.4142135623730951

In [57]:
map( x -> 2x+1 , a )

3×2 Matrix{Float64}:
 1.0      1.0
 3.82843  1.0
 1.0      1.0

In [58]:
g(x) = 2x+1

g (generic function with 1 method)

In [59]:
g.(a)

3×2 Matrix{Float64}:
 1.0      1.0
 3.82843  1.0
 1.0      1.0

In [60]:
a = ComplexF64.(a)

3×2 Matrix{ComplexF64}:
     0.0+0.0im  0.0+0.0im
 1.41421+0.0im  0.0+0.0im
     0.0+0.0im  0.0+0.0im

## Algèbre linéaire

On retrouve beaucoup (toutes) de fonctions usuelles de l'algèbre linéaire

In [61]:
using LinearAlgebra

In [62]:
A = SymTridiagonal(rand(5), rand(4))

5×5 SymTridiagonal{Float64, Vector{Float64}}:
 0.316355  0.658012   ⋅          ⋅          ⋅ 
 0.658012  0.770128  0.647429    ⋅          ⋅ 
  ⋅        0.647429  0.0561615  0.953217    ⋅ 
  ⋅         ⋅        0.953217   0.0952915  0.595363
  ⋅         ⋅         ⋅         0.595363   0.593309

In [63]:
det(A)

0.14474887421203098

In [64]:
tr(A)

1.831245417264069

In [65]:
eigvals(A)

5-element Vector{Float64}:
 -1.1148984308723155
 -0.18081685130603717
  0.40139852659881037
  1.1013271321711589
  1.624235040672453

In [66]:
inv(A)

5×5 Matrix{Float64}:
 -2.09452    2.52672   -0.876819  -1.6645     1.67026
  2.52672   -1.21478    0.421552   0.800247  -0.803017
 -0.876819   0.421552   0.389709   0.739799  -0.74236
 -1.6645     0.800247   0.739799  -0.587118   0.589151
  1.67026   -0.803017  -0.74236    0.589151   1.09427

In [67]:
b = collect(1:5); #résolution du système Ax=b
x = A \ b 

5-element Vector{Float64}:
 2.021770037502386
 0.547714937646882
 0.38280674053980546
 2.7526733814695397
 5.665107825824063

## Fonctions scientifiques et opérations

L'usage des fonction scientifiques se fait termes à termes pour l'ensemble des valeurs du tableau (sauf pour les fonctions matricielles comme `exp`, <code>log</code> ...). L'usage des opérations <code>+</code>,<code>-</code>,<code>\*</code>,<code>^</code>,<code>/</code> et `\`(résolution) est disponible à condition de respecter les contraintes de dimension (multiplication matricielle par exemple). Sont ajouté des opérations termes à termes <code>.\*</code>,<code>.^</code>,<code>./</code> et `.` toujours avec une contrainte de dimensions compatibles.

In [68]:
A=[1 2;3 4]
exp(A)

2×2 Matrix{Float64}:
  51.969   74.7366
 112.105  164.074

In [69]:
exp.(A) # exponentielle matricielle

2×2 Matrix{Float64}:
  2.71828   7.38906
 20.0855   54.5982

De plus les tableaux possèdes des opérations de multiplication, division, puissance termes à termes

In [70]:
A^2 #Multiplication Matricielle

2×2 Matrix{Int64}:
  7  10
 15  22

In [71]:
A.^2 #Multiplication terme à terme

2×2 Matrix{Int64}:
 1   4
 9  16

In [72]:
A ./ [2 3 ; 4 5] #Division terme à terme 

2×2 Matrix{Float64}:
 0.5   0.666667
 0.75  0.8

In [73]:
A./2

2×2 Matrix{Float64}:
 0.5  1.0
 1.5  2.0

## Opérateurs booléens sur les tableaux

In [74]:
A = collect(1:5)
A .> 2

5-element BitVector:
 0
 0
 1
 1
 1

In [75]:
collect(1:5) .> [0;2;3;4;5]

5-element BitVector:
 1
 0
 0
 0
 0

In [76]:
collect(1:5).>[0 2 3 4 5]

5×5 BitMatrix:
 1  0  0  0  0
 1  0  0  0  0
 1  1  0  0  0
 1  1  1  0  0
 1  1  1  1  0

## Particularité max, maximum, min, minimum

In [77]:
max(2,3)

3

In [78]:
max(1,2,3)

3

In [79]:
maximum(1:5)

5

In [80]:
?max

search: max map eigmax map! argmax imag minmax mark



```julia
max(x, y, ...)
```

Return the maximum of the arguments, with respect to [`isless`](@ref). If any of the arguments is [`missing`](@ref), return `missing`. See also the [`maximum`](@ref) function to take the maximum element from a collection.

# Examples

```jldoctest
julia> max(2, 5, 1)
5

julia> max(5, missing, 6)
missing
```


In [81]:
max.(1:5,2:6)

5-element Vector{Int64}:
 2
 3
 4
 5
 6

## Constructeurs

Enfin il est possible de construire rapidement certaines matrices

In [82]:
a = fill(0.,2,3) 

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [83]:
a=fill(2,2)

2-element Vector{Int64}:
 2
 2

In [84]:
b = range(0, stop=9, length=10)

0.0:1.0:9.0

In [85]:
b.offset, b.step, b.len

(1, Base.TwicePrecision{Float64}(1.0, 0.0), 10)

In [86]:
c = LinRange(0, 2π, 10)

10-element LinRange{Float64, Int64}:
 0.0, 0.698132, 1.39626, 2.0944, …, 4.18879, 4.88692, 5.58505, 6.28319

In [87]:
c.lendiv

9

In [88]:
collect(b)

10-element Vector{Float64}:
 0.0
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0

In [89]:
A=ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [90]:
A=zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [91]:
using Random

rng = Xoshiro(111)

B = randn(rng, 5) # loi normale centrée de variance 1

5-element Vector{Float64}:
 -1.2141570148792402
  0.8728141561713048
 -0.4473225480452905
  0.14532188192398446
 -0.8369753246696554

In [92]:
minimum(B), maximum(B)

(-1.2141570148792402, 0.8728141561713048)

In [93]:
extrema(B)

(-1.2141570148792402, 0.8728141561713048)

In [94]:
B = [ones(3,2) zeros(3,2)] # concaténation de tableaux

3×4 Matrix{Float64}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [95]:
hcat(ones(3,2), zeros(3,2))

3×4 Matrix{Float64}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [96]:
B=[ones(3,2); zeros(3,2)] # , ou ; jouent le rôle de retour à la ligne

6×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [97]:
vcat(ones(3,2), zeros(3,2))

6×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [98]:
C = Diagonal(ones(3,3))

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

In [99]:
A = rand(5,5)

display(A)

U, D, Vt = svd(A)

5×5 Matrix{Float64}:
 0.10765   0.556949  0.994658   0.975549  0.148471
 0.167919  0.846666  0.995862   0.936497  0.773192
 0.788216  0.412103  0.965627   0.153142  0.192688
 0.38077   0.161068  0.358468   0.157107  0.705683
 0.730452  0.566709  0.0434475  0.983855  0.491959

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
5×5 Matrix{Float64}:
 -0.49157   -0.3063     -0.497092  -0.318065  -0.562382
 -0.610794  -0.0712047  -0.285227   0.491334   0.546898
 -0.383997  -0.464738    0.679824  -0.368591   0.196328
 -0.249969   0.11774     0.443867   0.617773  -0.58736
 -0.41875    0.819308    0.111205  -0.374063   0.0330532
singular values:
5-element Vector{Float64}:
 2.858016086787226
 0.9235823895028659
 0.8619312293065586
 0.6123634624137222
 0.17365385884915785
Vt factor:
5×5 Matrix{Float64}:
 -0.300632   -0.429226   -0.551364   -0.546402  -0.350468
  0.251253    0.0659101  -0.808303    0.420011   0.32057
  0.794358   -0.120282    0.0486313  -0.543893   0.237366
 -0.457686   -0.0416893   0.0362748  -0.289973   0.838681
 -0.0775248   0.891748   -0.197391   -0.380962  -0.12116

In [100]:
A'A

5×5 Matrix{Float64}:
 1.33962   1.00224  1.20365  1.16146  0.925752
 1.00224   1.54397  1.87743  1.98221  1.20919
 1.20365   1.87743  3.04391  2.1499   1.37807
 1.16146   1.98221  2.1499   2.84483  1.49333
 0.925752  1.20919  1.37807  1.49333  1.39701

In [101]:
U * Diagonal(D) * Vt 

5×5 Matrix{Float64}:
  0.920675  -0.138423   -1.02006   0.613835   0.0272532
  0.490897  -0.0874034  -1.53183   0.785192  -0.0009135
  0.302471  -0.86154    -0.660804  0.63549   -0.331485
 -0.213799  -0.355381   -0.791942  0.141082  -0.0549231
  0.1053    -0.42267    -0.911093  0.590923   0.835215

In [102]:
diag(C) # extraction d'une diagonale

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [103]:
diagm(ones(3))

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [104]:
Matrix(I, 3, 3)

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

## type sparse

Julia possède un type sparse i.e. des matrices creuses, ces dernières ayant un comportement identique aux matrices elles ne diffèrent que dans leur définition (et leur stockage).

In [105]:
using SparseArrays

In [106]:
A = spzeros(3,3)

3×3 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅ 

In [107]:
A = spdiagm(0 => 1:3)

3×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [108]:
A = A + spdiagm(1 => 1:2)

3×3 SparseMatrixCSC{Int64, Int64} with 5 stored entries:
 1  1  ⋅
 ⋅  2  2
 ⋅  ⋅  3

In [109]:
nonzeros(A), nnz(A)

([1, 1, 2, 2, 3], 5)

In [110]:
sparse([0 1 2; 2 0 0]) # pour rendre sparse une matrice "full"

2×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  1  2
 2  ⋅  ⋅

In [111]:
det(A)

6.0

## Affectation et copie

Attention julia à un mode de passage de valeur qui fonctionne différemment suivant une variable type ou un tableau.

Pour une variable scalaire

In [112]:
a = 1
b = a
b += 1

2

In [113]:
a

1

In [114]:
b

2

In [115]:
a

1

Par contre maintenant si la variable est un tableau

In [116]:
A = collect(1:5)
B = A
B .+= 1

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [117]:
A

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [118]:
B

5-element Vector{Int64}:
 2
 3
 4
 5
 6

Pour avoir un comportement il faut copier le tableau A 

In [119]:
A = collect(1:5)
B = copy(A)
B .= B .+ 1

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [120]:
A

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [121]:
B

5-element Vector{Int64}:
 2
 3
 4
 5
 6

Il faut faire attention à ce comportement lorsque l'on utilise des vecteurs de vecteurs

In [127]:
A = collect(1:5)
vecs = [A for i in 1:3]


3-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5]
 [1, 2, 3, 4, 5]
 [1, 2, 3, 4, 5]

In [128]:
A .+= 1
vecs

3-element Vector{Vector{Int64}}:
 [2, 3, 4, 5, 6]
 [2, 3, 4, 5, 6]
 [2, 3, 4, 5, 6]

In [129]:
A .*= -1

5-element Vector{Int64}:
 -2
 -3
 -4
 -5
 -6

In [130]:
B

5-element Vector{Int64}:
 -2
 -3
 -4
 -5
 -6

In [131]:
B .= A

5-element Vector{Int64}:
 -2
 -3
 -4
 -5
 -6

In [132]:
vecs[1] .*= 2

5-element Vector{Int64}:
  -4
  -6
  -8
 -10
 -12

In [138]:
vecs

3-element Vector{Vector{Int64}}:
 [-4, -6, -8, -10, -12]
 [-4, -6, -8, -10, -12]
 [-4, -6, -8, -10, -12]

In [142]:
A = collect(1:5)
vecs = [copy(A) for i in 1:3]
vecs[1] .*= 2
vecs

3-element Vector{Vector{Int64}}:
 [2, 4, 6, 8, 10]
 [1, 2, 3, 4, 5]
 [1, 2, 3, 4, 5]

# Dictionnaire

In [143]:
typeof(:A)

Symbol

In [144]:
d = Dict(:key1 => "val1", :key2 => "val2")

Dict{Symbol, String} with 2 entries:
  :key2 => "val2"
  :key1 => "val1"

In [145]:
keys(d) # Toutes clés (itérateur)

KeySet for a Dict{Symbol, String} with 2 entries. Keys:
  :key2
  :key1

In [146]:
values(d) # Toutes valeurs (itérateur)

ValueIterator for a Dict{Symbol, String} with 2 entries. Values:
  "val2"
  "val1"

In [147]:
for (k,v) in d # Itérer par paire clé-valeur
    println("key: $k, value: $v")
end

key: key2, value: val2
key: key1, value: val1


In [148]:
haskey(d, :k) # Vérifier la présence de la clé :k

false

Les dictionnaires sont muables; quand des symboles sont utilisés comme clés, les clés sont immuables.

In [ ]:
let s = 0 
    for x in 1:1000
        if x %3 == 0 || x % 5 == 0
            s += x
        end
    end
    println(s)
end

In [154]:
try
   println(s)
catch e
    println(e)
end

UndefVarError(:s, 0x0000000000009738, Main)


In [155]:
sum( x for x in 1:1000 if (x%3 == 0 || x % 5 ==0))

234168

In [156]:
sum(filter(x -> (x%3 == 0 || x % 5 ==0), 1:1000))

234168