# Tableaux et matrices

La définition de tableaux i.e. vecteurs, matrices, hypermatrices est un élément essentiel de Julia.

Julia ne possède qu'un seul type de tableau : **Array** on peut définir son nombre d'entrées (1 entrée= 1 dimension ...) et son contenu de façon assez générale. Un tableau peut contenir des matrices à chaque élément.

Une particularité est que les indices de tableaux commencent à 1, et l'accès aux éléments se fera à l'aide de `[` `]` et non `(` `)` qui est réservé aux fonctions.

Avant de rentrer dans la construction et manipulation de tableau regardons une autre classe 

# Iterateur

Julia possède un Type particulier fait à l'aide du ":"

In [1]:
a = 1:5

1:5

In [2]:
a .+ 1

2:6

In [3]:
typeof(a)

UnitRange{Int64}

In [4]:
b=0:0.5:2

0.0:0.5:2.0

In [5]:
typeof(b)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

Ce type "formel" permet d'avoir une définition et une méthode associée sans stocker l'ensemble des valeurs. Attention celui-ci peut être vide :

In [6]:
d=1:0 # itérateur formel mais correspond à un ensemble vide de valeurs

1:0

In [9]:
d  = 1:10  |> collect

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

# Tableau

On vient de voir que l'on peut transformer l'itérateur précédent en tableau à l'aide de la commande "collect"

In [15]:
a=1:5
aa=collect(complex.(a)) .+ 1im

5-element Vector{Complex{Int64}}:
 1 + 1im
 2 + 1im
 3 + 1im
 4 + 1im
 5 + 1im

In [16]:
collect(aa')

1×5 Matrix{Complex{Int64}}:
 1-1im  2-1im  3-1im  4-1im  5-1im

In [17]:
transpose(aa)

1×5 transpose(::Vector{Complex{Int64}}) with eltype Complex{Int64}:
 1+1im  2+1im  3+1im  4+1im  5+1im

In [22]:
a  .* a'

5×5 Matrix{Int64}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [24]:
typeof(aa)

Vector{Complex{Int64}} (alias for Array{Complex{Int64}, 1})

La réponse est de la forme **Array{Type,dim}** un tableau de **Type** à **dim** entrées (1 pour vecteur, 2 pour matrices ...)

A remarquer :
* l'indexation des tableaux commence à 1.
* un tableau à une entrée est vu comme un vecteur colonne par défaut.
* le crochet [ ] sert à extraire ou affecter une valeur ou un bloc de valeur. Attention le crochet [ ] sert également de "concatenateur" et constructeur de tableau (voir suite)
* Il est possible de faire des tableaux de n'importe quoi (fonction, tableau, ...).

In [25]:
aa[1]

1 + 1im

In [26]:
aa[begin] # pour accèder au premier élément

1 + 1im

In [27]:
aa[end] # pour accèder au dernier élément

5 + 1im

In [28]:
first(a), last(a)

(1, 5)

In [29]:
aa[end-2:end].=1; println(aa)

Complex{Int64}[1 + 1im, 2 + 1im, 1 + 0im, 1 + 0im, 1 + 0im]


Les crochets permettent la construction explicite de tableaux (ou leur concaténation)

In [30]:
A=[1 2 ; 3 4] # {espace} = séparateur de colonne

2×2 Matrix{Int64}:
 1  2
 3  4

In [31]:
AA=[A  A] # concaténation par bloc

2×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4

In [32]:
hcat(A,A) # commande équivalent à la précédente [A  A]

2×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4

In [33]:
AA=[A ; A]

4×2 Matrix{Int64}:
 1  2
 3  4
 1  2
 3  4

In [34]:
vcat(A,A) # commande équivalent à la précédente [A  ; A]

4×2 Matrix{Int64}:
 1  2
 3  4
 1  2
 3  4

On peut accéder à tout ou partie d'un tableau à l'aide de 2 indices

In [35]:
A[2,1]

3

In [36]:
A[2,:]

2-element Vector{Int64}:
 3
 4

In [37]:
A[:,2]

2-element Vector{Int64}:
 2
 4

In [38]:
A[end,end]

4

In [39]:
sum(AA, dims=1)

1×2 Matrix{Int64}:
 8  12

In [40]:
B=[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [41]:
B=[1;2;3;4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [47]:
for i in eachindex(AA)
    println(i)
end

1
2
3
4
5
6
7
8


In [56]:
for (i,row) ∈ enumerate(AA)
    println("$i - $row")
end

1 - 1
2 - 3
3 - 1
4 - 3
5 - 2
6 - 4
7 - 2
8 - 4


A noter que l'on peut faire des tableaux de tout type voir de les mélanger (Any)

In [57]:
a=["un";"deux"]

2-element Vector{String}:
 "un"
 "deux"

In [58]:
b=[1>2,true,false]

3-element Vector{Bool}:
 0
 1
 0

In [59]:
c=["un"; 2 ; true]

3-element Vector{Any}:
     "un"
    2
 true

Le crochet [ ] permet également la construction rapide de matrice ou tableau comme le montre l'exemple ci-dessous pour construire une matrice de VanderMonde

$$ V_{i,j}=x_i^{j-1}$$

In [52]:
x=0:0.2:1;
V=[ x[i]^(j-1) for i=1:6, j=1:6] # ligne et colonne

6×6 Matrix{Float64}:
 1.0  0.0  0.0   0.0    0.0     0.0
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0

In [53]:
D=[ u*v for u=1:0.5:3, v=1:0.5:4]

5×7 Matrix{Float64}:
 1.0  1.5   2.0  2.5   3.0   3.5    4.0
 1.5  2.25  3.0  3.75  4.5   5.25   6.0
 2.0  3.0   4.0  5.0   6.0   7.0    8.0
 2.5  3.75  5.0  6.25  7.5   8.75  10.0
 3.0  4.5   6.0  7.5   9.0  10.5   12.0

On peux évidemment faire des tableaux à 3,4... entrèes.

## Manipulation de Tableau

### push!

Le fonction push permet d'ajouter à un tableau une valeur supplémentaire

In [60]:
a=[]
push!(a,1)     # => [1]
push!(a,2)     # => [1,2]
push!(a,4)     # => [1,2,4]
push!(a,6)     # => [1,2,4,6]

4-element Vector{Any}:
 1
 2
 4
 6

### append!

Cette fonction permet de mettre bout à bout 2 tableaux

In [61]:
append!(a,a)

8-element Vector{Any}:
 1
 2
 4
 6
 1
 2
 4
 6

A noté le  **Array{Any,1}** !

In [64]:
a = ComplexF64[]
push!(a,1)     # => [1]
push!(a,2)     # => [1,2]
push!(a,4)     # => [1,2,4]
push!(a,6)  

4-element Vector{ComplexF64}:
 1.0 + 0.0im
 2.0 + 0.0im
 4.0 + 0.0im
 6.0 + 0.0im

In [65]:
a = zeros(0)

Float64[]

In [66]:
a = zeros(Int32,1)

1-element Vector{Int32}:
 0

In [67]:
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [69]:
fill(5, 6)

6-element Vector{Int64}:
 5
 5
 5
 5
 5
 5

### Attention sur la conversion de type !

In [70]:
a=collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [72]:
a=fill(0.,3,2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [73]:
a[2]=sqrt(2)

1.4142135623730951

In [75]:
a = map(ComplexF64,a)

3×2 Matrix{ComplexF64}:
     0.0+0.0im  0.0+0.0im
 1.41421+0.0im  0.0+0.0im
     0.0+0.0im  0.0+0.0im

In [78]:
a=ComplexF64.(a)

3×2 Matrix{ComplexF64}:
     0.0+0.0im  0.0+0.0im
 1.41421+0.0im  0.0+0.0im
     0.0+0.0im  0.0+0.0im

## Algèbre linéaire

On retrouve beaucoup (toutes) de fonctions usuelles de l'algèbre linéaire

In [79]:
using LinearAlgebra

In [80]:
A=[1 2 ; 3 4]
size(A)

(2, 2)

In [81]:
det(A)

-2.0

In [82]:
tr(A)

5

In [83]:
eigvals(A)

2-element Vector{Float64}:
 -0.3722813232690143
  5.372281323269014

In [84]:
A = [1 2; 3 4]
b =[2 ; 3]; #résolution du système Ax=b
x = A \ b 

2-element Vector{Float64}:
 -0.9999999999999997
  1.4999999999999998

## Fonctions scientifiques et opérations

L'usage des fonction scientifiques se fait termes à termes pour l'ensemble des valeurs du tableau (sauf pour les fonctions matricielles comme `exp`, <code>log</code> ...). L'usage des opérations <code>+</code>,<code>-</code>,<code>\*</code>,<code>^</code>,<code>/</code> et `\`(résolution) est disponible à condition de respecter les contraintes de dimension (multiplication matricielle par exemple). Sont ajouté des opérations termes à termes <code>.\*</code>,<code>.^</code>,<code>./</code> et `.` toujours avec une contrainte de dimensions compatibles.

In [85]:
A=[1 2;3 4]
exp(A)

2×2 Matrix{Float64}:
  51.969   74.7366
 112.105  164.074

In [86]:
exp.(A) # exponentielle matricielle

2×2 Matrix{Float64}:
  2.71828   7.38906
 20.0855   54.5982

De plus les tableaux possèdes des opérations de multiplication, division, puissance termes à termes

In [87]:
A^2 #Multiplication Matricielle

2×2 Matrix{Int64}:
  7  10
 15  22

In [88]:
A.^2 #Multiplication terme à terme

2×2 Matrix{Int64}:
 1   4
 9  16

In [89]:
A./[2 3 ; 4 5] #Division terme à terme 

2×2 Matrix{Float64}:
 0.5   0.666667
 0.75  0.8

In [90]:
A./2

2×2 Matrix{Float64}:
 0.5  1.0
 1.5  2.0

## Opérateurs booléens sur les tableaux

In [91]:
collect(1:5)>2

LoadError: MethodError: no method matching isless(::Int64, ::Vector{Int64})
Closest candidates are:
  isless(::AbstractVector, ::AbstractVector) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/abstractarray.jl:2532
  isless(::Real, ::AbstractFloat) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/operators.jl:185
  isless(::Real, ::Real) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/operators.jl:430
  ...

In [92]:
collect(1:5).>2

5-element BitVector:
 0
 0
 1
 1
 1

In [93]:
collect(1:5).>[0;2;3;4;5]

5-element BitVector:
 1
 0
 0
 0
 0

In [94]:
collect(1:5).>[0 2 3 4 5]

5×5 BitMatrix:
 1  0  0  0  0
 1  0  0  0  0
 1  1  0  0  0
 1  1  1  0  0
 1  1  1  1  0

## Particularité max, maximum, min, minimum

In [95]:
max(2,3)

3

In [96]:
max(1,2,3)

3

In [97]:
max(1:5)

LoadError: MethodError: no method matching max(::UnitRange{Int64})
Closest candidates are:
  max(::Any, ::Missing) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/missing.jl:137
  max(::Any, ::Any) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/operators.jl:492
  max(::Any, ::Any, ::Any, ::Any...) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/operators.jl:655
  ...

In [101]:
?max

search: max maximum maximum! maxintfloat argmax eigmax RowMaximum typemax



```
max(x, y, ...)
```

Return the maximum of the arguments (with respect to [`isless`](@ref)). See also the [`maximum`](@ref) function to take the maximum element from a collection.

# Examples

```jldoctest
julia> max(2, 5, 1)
5
```


In [99]:
max.(1:5,2:6)

5-element Vector{Int64}:
 2
 3
 4
 5
 6

## Constructeurs

Enfin il est possible de construire rapidement certaines matrices

In [102]:
a=fill(0.,2,3) 

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [103]:
a=fill(2,2)

2-element Vector{Int64}:
 2
 2

In [104]:
b=range(0,stop=2*pi,length=10)

0.0:0.6981317007977318:6.283185307179586

In [106]:
?range

search: range LinRange UnitRange StepRange StepRangeLen trailing_zeros



```
range(start, stop, length)
range(start, stop; length, step)
range(start; length, stop, step)
range(;start, length, stop, step)
```

Construct a specialized array with evenly spaced elements and optimized storage (an [`AbstractRange`](@ref)) from the arguments. Mathematically a range is uniquely determined by any three of `start`, `step`, `stop` and `length`. Valid invocations of range are:

  * Call `range` with any three of `start`, `step`, `stop`, `length`.
  * Call `range` with two of `start`, `stop`, `length`. In this case `step` will be assumed

to be one. If both arguments are Integers, a [`UnitRange`](@ref) will be returned.

# Examples

```jldoctest
julia> range(1, length=100)
1:100

julia> range(1, stop=100)
1:100

julia> range(1, step=5, length=100)
1:5:496

julia> range(1, step=5, stop=100)
1:5:96

julia> range(1, 10, length=101)
1.0:0.09:10.0

julia> range(1, 100, step=5)
1:5:96

julia> range(stop=10, length=5)
6:10

julia> range(stop=10, step=1, length=5)
6:1:10

julia> range(start=1, step=1, stop=10)
1:1:10
```

If `length` is not specified and `stop - start` is not an integer multiple of `step`, a range that ends before `stop` will be produced.

```jldoctest
julia> range(1, 3.5, step=2)
1.0:2.0:3.0
```

Special care is taken to ensure intermediate values are computed rationally. To avoid this induced overhead, see the [`LinRange`](@ref) constructor.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.


!!! compat "Julia 1.7"
    The versions without keyword arguments and `start` as a keyword argument require at least Julia 1.7.



In [107]:
c = LinRange(0, 2π, 10)

10-element LinRange{Float64, Int64}:
 0.0,0.698132,1.39626,2.0944,2.79253,3.49066,4.18879,4.88692,5.58505,6.28319

In [108]:
?LinRange

search: LinRange



```
LinRange{T,L}
```

A range with `len` linearly spaced elements between its `start` and `stop`. The size of the spacing is controlled by `len`, which must be an `Integer`.

# Examples

```jldoctest
julia> LinRange(1.5, 5.5, 9)
9-element LinRange{Float64, Int64}:
 1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5
```

Compared to using [`range`](@ref), directly constructing a `LinRange` should have less overhead but won't try to correct for floating point errors:

```julia
julia> collect(range(-0.1, 0.3, length=5))
5-element Array{Float64,1}:
 -0.1
  0.0
  0.1
  0.2
  0.3

julia> collect(LinRange(-0.1, 0.3, 5))
5-element Array{Float64,1}:
 -0.1
 -1.3877787807814457e-17
  0.09999999999999999
  0.19999999999999998
  0.3
```


In [109]:
collect(b)

10-element Vector{Float64}:
 0.0
 0.6981317007977318
 1.3962634015954636
 2.0943951023931953
 2.792526803190927
 3.490658503988659
 4.1887902047863905
 4.886921905584122
 5.585053606381854
 6.283185307179586

In [110]:
A=ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [111]:
A=zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [115]:
using Random

rng = MersenneTwister(111)

B=randn(rng, 5) # loi normale centrée de variance 1

5-element Vector{Float64}:
 0.3903857587906403
 0.4853575063504947
 0.5192651920426572
 0.0579310229221599
 0.8452934490343489

In [116]:
B=[ones(3,2) zeros(3,2)] # concaténation de tableaux

3×4 Matrix{Float64}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [117]:
B=[ones(3,2); zeros(3,2)] # , ou ; jouent le rôle de retour à la ligne

6×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [118]:
C = Diagonal(ones(3,3))

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

In [119]:
diag(C) # extraction d'une diagonale

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [120]:
diagm(ones(3))

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [121]:
Matrix(I, 3, 3)

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

## type sparse

Julia possède un type sparse i.e. des matrices creuses, ces dernières ayant un comportement identique aux matrices elles ne diffèrent que dans leur définition (et leur stockage).

In [122]:
using SparseArrays

In [123]:
A=spzeros(3,3)

3×3 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅ 

In [124]:
A=spdiagm(0 => 1:3)

3×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [125]:
A=A+spdiagm(1 => 1:2)

3×3 SparseMatrixCSC{Int64, Int64} with 5 stored entries:
 1  1  ⋅
 ⋅  2  2
 ⋅  ⋅  3

In [126]:
sparse([0 1 2; 2 0 0]) # pour rendre sparse une matrice "full"

2×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  1  2
 2  ⋅  ⋅

In [127]:
det(A)

6.0

## Affectation et copie

Attention julia à un mode de passage de valeur qui fonctionne différemment suivant une variable type ou un tableau.

Pour une variable scalaire

In [128]:
a = 1
b = a
b += 1

2

In [129]:
a

1

In [131]:
b

2

In [132]:
a

1

Par contre maintenant si la variable est un tableau

In [133]:
A = collect(1:5)
B = A
B .+= 1

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [134]:
A

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [135]:
B

5-element Vector{Int64}:
 2
 3
 4
 5
 6

Pour avoir un comportement il faut copier le tableau A 

In [139]:
A = collect(1:5)
B = copy(A)
@. B = B + 1

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [140]:
A

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [141]:
B

5-element Vector{Int64}:
 2
 3
 4
 5
 6

# Dictionnaire

In [142]:
d = Dict(:key1 => "val1", :key2 => "val2")

Dict{Symbol, String} with 2 entries:
  :key2 => "val2"
  :key1 => "val1"

In [143]:
keys(d) # Toutes clés (itérateur)

KeySet for a Dict{Symbol, String} with 2 entries. Keys:
  :key2
  :key1

In [144]:
values(d) # Toutes valeurs (itérateur)

ValueIterator for a Dict{Symbol, String} with 2 entries. Values:
  "val2"
  "val1"

In [145]:
for (k,v) in d # Itérer par paire clé-valeur
    println("key: $k, value: $v")
end

key: key2, value: val2
key: key1, value: val1


In [146]:
haskey(d, :k) # Vérifier la présence de la clé :k

false

Les dictionnaires sont muables; quand des symboles sont utilisés comme clés, les clés sont immuables.